name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: wtfjoke/setup-tectonic@v3
    - run: make -B
    - name: Upload resume
      uses: actions/upload-artifact@v4
      with:
        name: resume
        path: dilawar.pdf
